---
- hosts: webservers
  become: yes
  tasks:
    - name: Running the container
      docker_container:
        name: "mywebserver"
        image: "aronaba/mywebserver:v1"
        ports:
          - "80:80"
        state: started

    - name: Check if container is running
      shell: docker ps
