---
- hosts: webservers
  become: yes
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
    - name: install docker-py package
      pip: name=docker-py
      
    - name: delete container if exist
      docker_container:
        name: "mywebserver"
        image: "aronaba/mywebserver:v1"
        state: absent
      
    - name: Running the container
      docker_container:
        name: "mywebserver"
        image: "aronaba/mywebserver:v1"
        ports:
          - "80:80"
        state: started

    - name: Check if container is running
      shell: docker ps
